-- Código de Triggers utilizados -- 

-- Trigger para a tabela CLIENTE
CREATE OR REPLACE TRIGGER tr_auditar_cliente
AFTER INSERT OR UPDATE OR DELETE ON CLIENTE
FOR EACH ROW
EXECUTE FUNCTION trg_auditoria_generica();

-- Trigger para a tabela FUNCIONARIO
CREATE OR REPLACE TRIGGER tr_auditar_funcionario
AFTER INSERT OR UPDATE OR DELETE ON FUNCIONARIO
FOR EACH ROW
EXECUTE FUNCTION trg_auditoria_generica();

-- Trigger para a tabela TIPO_LAVAGEM
CREATE OR REPLACE TRIGGER tr_auditar_tipo_lavagem
AFTER INSERT OR UPDATE OR DELETE ON TIPO_LAVAGEM
FOR EACH ROW
EXECUTE FUNCTION trg_auditoria_generica();

-- Trigger para a tabela TIPO_PAGAMENTO
CREATE OR REPLACE TRIGGER tr_auditar_tipo_pagamento
AFTER INSERT OR UPDATE OR DELETE ON TIPO_PAGAMENTO
FOR EACH ROW
EXECUTE FUNCTION trg_auditoria_generica();

-- Trigger para a tabela FORNECEDOR
CREATE OR REPLACE TRIGGER tr_auditar_fornecedor
AFTER INSERT OR UPDATE OR DELETE ON FORNECEDOR
FOR EACH ROW
EXECUTE FUNCTION trg_auditoria_generica();

-- Trigger para a tabela PRODUTO
CREATE OR REPLACE TRIGGER tr_auditar_produto
AFTER INSERT OR UPDATE OR DELETE ON PRODUTO
FOR EACH ROW
EXECUTE FUNCTION trg_auditoria_generica();

-- Trigger para a tabela COMPRA
CREATE OR REPLACE TRIGGER tr_auditar_compra
AFTER INSERT OR UPDATE OR DELETE ON COMPRA
FOR EACH ROW
EXECUTE FUNCTION trg_auditoria_generica();

-- Trigger para a tabela ITEM
CREATE OR REPLACE TRIGGER tr_auditar_item
AFTER INSERT OR UPDATE OR DELETE ON ITEM
FOR EACH ROW
EXECUTE FUNCTION trg_auditoria_generica();

-- Trigger para a tabela LAVAGEM
CREATE OR REPLACE TRIGGER tr_auditar_lavagem
AFTER INSERT OR UPDATE OR DELETE ON LAVAGEM
FOR EACH ROW
EXECUTE FUNCTION trg_auditoria_generica();

-- Trigger para a tabela PARCELA
CREATE OR REPLACE TRIGGER tr_auditar_parcela
AFTER INSERT OR UPDATE OR DELETE ON PARCELA
FOR EACH ROW
EXECUTE FUNCTION trg_auditoria_generica();

-- Trigger para a tabela LAVAGEM_PRODUTO
CREATE OR REPLACE TRIGGER tr_audistar_lavagem_produto
AFTER INSERT OR UPDATE OR DELETE ON LAVAGEM_PRODUTO
FOR EACH ROW
EXECUTE FUNCTION trg_auditoria_generica();