-- Codigo para povoamento da tabela --

-------------------- Criação de tabelas -------------------- 
-- Precisa ajeitar as chaves estragenrias, usando references --
CREATE TABLE CLIENTE (
    ID_CLIENTE SERIAL PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL, 
    CPF VARCHAR(15) UNIQUE NOT NULL,
    DT_NASC DATE,
    TELEFONE VARCHAR(20),
    EMAIL VARCHAR(100),
    ENDERECO VARCHAR(255),
    PREFERENCIAS_LAVAGEM TEXT,
    DATA_CADASTRO DATE DEFAULT CURRENT_DATE,
    ULTIMO_SERVICO DATE
);


CREATE TABLE TIPO_PAGAMENTO (
	ID_TIPO_PAGAMENTO SERIAL PRIMARY KEY,
	DESCRICAO VARCHAR(70) NOT NULL
)

CREATE TABLE FUNCIONARIO (
	ID_FUNCIONARIO SERIAL PRIMARY KEY
	NOME VARCHAR(100) NOT NULL,
	CPF VARCHAR(15) UNIQUE NOT NULL,
	CARGA VARCHAR(50),
	DT_CONTRATACAO DATE,
	TELEFONE VARCHAR(20)
	EMAIL VARCHAR(100)
	SALARIO DECIMAL(10,2)
)

CREATE TABLE LAVAGEM (
	ID_LAVAGEM SERIAL PRIMARY KEY,
	ID_CLIENTE INT NOT NULL
	ID_FUNCIONARIO INT NOT NULL,
	ID_TIPO_LAVAGEM INT NOT NULL,
	DT_ENTRADA TIMESTAMP NOT NULL,
	-- Entrega no sentido de pedido estar pronto --
	DT_PREV_ENTREGA TIMESTAMP,
	DT_REAL_ENTREGA TIMESTAMP,
	STATUS_LAVAGEM VARCHAR(50) NOT NULL,
	VALOR_TOTAL DECIMAL(10,2) NOT NULL,
	OBSERVACOES TEXT
)

CREATE TABLE TIPO_LAVAGEM(
	ID_TIPO_LAVAGEM SERIAL PRIMARY KEY,
	DESCRICAO VARCHAR(100) NOT NULL,
	PRECO_POR_KG DECIMAL(10,2),
	PRECO_FIXO DECIMAL(10,2),
	UNIDADE_MEDIDA VARCHAR(20)
)

CREATE TABLE PRODUTO (
	ID_PRODUTO SERIAL PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL,
	DESCRICAO TEXT,
	UNIDADE_MEDIDA VARCHAR(20),
	QTD_PRODUTO DECIMAL(10,2)
)

CREATE TABLE ITEM (
	ID_ITEM SERIAL PRIMARY KEY,
	ID_LAVAGEM INT NOT NULL,
	ID_PRODUTO INT NOT NULL,
	DESCRICAO_ITEM VARCHAR(100) NOT NULL
	QTD_ITEM INT NOT NULL,
	PESO_KG DECIMAL(10,2),
	VALOR_ITEM DECIMAL(10,2),
	OBESERVACOES TEXT
)

CREATE TABLE COMPRA(
	ID_COMPRA SERIAL PRIMARY KEY,
	ID_FORNECEDOR INT NOT NULL,
	DT_COMPRA DATE NOT NULL,
	VALOR_TOTAL DECIMAL(10,2) NOT NULL,
	STATUS_COMPRA VARCHAR(50)
)

CREATE TABLE PARCELA(
	ID_PARCELA SERIAL PRIMARY KEY,
	ID_LAVAGEM INT NOT NULL,
	NUM_PARCELA INT NOT NULL,
	DT_VENCIMENTO DATE NOT NULL,
	DT_PAGAMENTO DATE NOT NULL,
	STATUS_PARCELA VARCHAR(50) NOT NULL,
	ID_TIPO_PAGAMENTO INT NOT NULL
)
------------------------------------------------------------
