-------------------- TABELAS PRINCIPAIS --------------------

CREATE TABLE CLIENTE (
    ID_CLIENTE SERIAL PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL, 
    CPF VARCHAR(15) UNIQUE NOT NULL, --- UNIQUE impõe que todos os valores de uma coluna (ou combinação de colunas) sejam exclusivos
    DT_NASC DATE,
    TELEFONE VARCHAR(20),
    EMAIL VARCHAR(100),
    ENDERECO VARCHAR(255),
    PREFERENCIAS_LAVAGEM TEXT,
    DATA_CADASTRO DATE DEFAULT CURRENT_DATE, --- DATA_CADASTRO como do tipo DATE e, se nenhum valor for informado ao inserir um registro, o banco atribui automaticamente a data atual (hoje) àquele campo.
    ULTIMO_SERVICO DATE
);

CREATE TABLE FUNCIONARIO (
    ID_FUNCIONARIO SERIAL PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(15) UNIQUE NOT NULL,
    CARGO VARCHAR(50),
    DT_CONTRATACAO DATE,
    TELEFONE VARCHAR(20),
    EMAIL VARCHAR(100),
    SALARIO DECIMAL(10,2)
);

CREATE TABLE TIPO_LAVAGEM (
    ID_TIPO_LAVAGEM SERIAL PRIMARY KEY,
    DESCRICAO VARCHAR(100) NOT NULL,
    PRECO_POR_KG DECIMAL(10,2),
    PRECO_FIXO DECIMAL(10,2),
    UNIDADE_MEDIDA VARCHAR(20)
);

CREATE TABLE TIPO_PAGAMENTO (
    ID_TIPO_PAGAMENTO SERIAL PRIMARY KEY,
    DESCRICAO VARCHAR(70) NOT NULL
);

CREATE TABLE FORNECEDOR (
    ID_FORNECEDOR SERIAL PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    CNPJ VARCHAR(20) UNIQUE,
    TELEFONE VARCHAR(20),
    EMAIL VARCHAR(100),
    ENDERECO VARCHAR(255)
);

-------------------- PROCESSOS --------------------

CREATE TABLE PRODUTO (
    ID_PRODUTO SERIAL PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    DESCRICAO TEXT,
    UNIDADE_MEDIDA VARCHAR(20) NOT NULL,
    QTD_ESTOQUE DECIMAL(10,2) NOT NULL CHECK (QTD_ESTOQUE >= 0)
);

CREATE TABLE COMPRA (
    ID_COMPRA SERIAL PRIMARY KEY,
    fk_compra_fornecedor INT REFERENCES FORNECEDOR(ID_FORNECEDOR),
    DT_COMPRA DATE NOT NULL,
    VALOR_TOTAL DECIMAL(10,2) NOT NULL,
    STATUS_COMPRA VARCHAR(50) CHECK (STATUS_COMPRA IN ('PENDENTE','ENTREGUE','CANCELADA'))  --- Cria uma restrição de verificação (CHECK) que só permite que ela assuma valores informados.
);

CREATE TABLE ITEM (
    ID_ITEM SERIAL PRIMARY KEY,
    fk_item_compra INT REFERENCES COMPRA(ID_COMPRA),
    fk_item_produto INT REFERENCES PRODUTO(ID_PRODUTO),
    DESCRICAO_ITEM VARCHAR(100) NOT NULL,
    QTD_ITEM DECIMAL(10,2) NOT NULL CHECK (QTD_ITEM > 0),
    VALOR_UNITARIO DECIMAL(10,2) NOT NULL,
    VALOR_TOTAL DECIMAL(10,2) GENERATED ALWAYS AS (QTD_ITEM * VALOR_UNITARIO) STORED
);

/*
GENERATED ALWAYS AS (QTD_ITEM * VALOR_UNITARIO) indica que o valor dessa coluna será sempre o resultado da multiplicação entre QTD_ITEM e VALOR_UNITARIO.
STORED significa que esse cálculo é feito no momento da inserção/atualização e armazenado fisicamente no banco. 
*/

-------------------- LAVAGEM E FINANCEIRO --------------------

CREATE TABLE LAVAGEM (
    ID_LAVAGEM SERIAL PRIMARY KEY,
    fk_lavagem_cliente INT REFERENCES CLIENTE(ID_CLIENTE),
    fk_lavagem_funcionario INT REFERENCES FUNCIONARIO(ID_FUNCIONARIO),
    fk_lavagem_tipo INT REFERENCES TIPO_LAVAGEM(ID_TIPO_LAVAGEM),
    fk_lavagem_pagamento INT REFERENCES TIPO_PAGAMENTO(ID_TIPO_PAGAMENTO),
    DT_ENTRADA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DT_PREV_ENTREGA TIMESTAMP,
    DT_REAL_ENTREGA TIMESTAMP,
    STATUS_LAVAGEM VARCHAR(50) NOT NULL CHECK (STATUS_LAVAGEM IN ('EM ANDAMENTO','CONCLUIDA','CANCELADA')),
    OBSERVACOES TEXT
);

CREATE TABLE PARCELA (
    ID_PARCELA SERIAL PRIMARY KEY,
    fk_parcela_lavagem INT REFERENCES LAVAGEM(ID_LAVAGEM),
    NUM_PARCELA INT NOT NULL,
    VALOR_PARCELA DECIMAL(10,2) NOT NULL,
    DT_VENCIMENTO DATE NOT NULL,
    DT_PAGAMENTO DATE,
    STATUS_PARCELA VARCHAR(50) NOT NULL CHECK (STATUS_PARCELA IN ('PAGO','PENDENTE','ATRASADO'))
);

-------------------- RELACIONAMENTO USO DE PRODUTOS NA LAVAGEM --------------------

CREATE TABLE LAVAGEM_PRODUTO (
    fk_lavagem_produto_lavagem INT REFERENCES LAVAGEM(ID_LAVAGEM),
    fk_lavagem_produto_produto INT REFERENCES PRODUTO(ID_PRODUTO),
    QTD_UTILIZADA DECIMAL(10,2) NOT NULL CHECK (QTD_UTILIZADA > 0),
    PRIMARY KEY (fk_lavagem_produto_lavagem, fk_lavagem_produto_produto)
);